config/routes.rb
EnginedCmf::Application.routes.draw do

  scope '/admin' do
    devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }, :path => 'auth',
      :controllers => { :sessions => 'engined_cmf/devise/sessions', :passwords => 'engined_cmf/devise/passwords', :unlocks => 'engined_cmf/devise/unlocks' }
  end

  namespace :admin, :module => 'engined_cmf' do
    get '/' => 'index#index', :as => 'root'
    get '/profile' => 'profile#edit', :as => 'profile'
    put '/profile' => 'profile#update'

    get '/files' => 'files#index', :as => 'files'
    match '/files/elfinder' => 'files#elfinder', :as => 'elfinder'

    resources :users, :roles, :dynamic_pages
    resources :references do
      resources :images, :except => [ :show, :edit, :update ]
    end

    match '/thumbnail/:width/:height/:process/*path' => 'thumbnail#show',
      :as => 'thumbnail',
      :constraints => { :width => /\d+/, :height => /\d+/, :process => /\d+/ }
  end

  root :to => 'index#index'
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  has_many :images, :as => :imageable, :autosave => true, :dependent => :destroy
  has_one :page, :as => :pageable, :autosave => true, :dependent => :destroy

  accepts_nested_attributes_for :page
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => lambda { |i| i[:url].blank? }

  attr_accessible :city, :content, :page_attributes, :images_attributes, :image

  has_friendly_id :alias, :use_slug => true, :approximate_ascii => true

  validates_presence_of :city, :content

  def initialize(attributes = nil)
    self.page = Page.new
    super(attributes)
  end

  def title
    page.title
  end

  def alias
    page.alias
  end

end

app/controllers/engined_cmf/application_controller.rb
class EnginedCmf::ApplicationController < ApplicationController
  unloadable

  before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    sign_out current_user
    redirect_to user_root_url, :alert => exception.message
  end

  layout 'engined_cmf/application.html.haml'

  # Sets the flash message with :key, using I18n. By default you are able
  # to setup your messages using specific resource scope, and if no one is
  # found we look to default scope.
  # Example (i18n locale file):
  #
  #   en:
  #     devise:
  #       passwords:
  #         #default_scope_messages - only if resource_scope is not found
  #         user:
  #           #resource_scope_messages
  #
  # Please refer to README or en.yml locale file to check what messages are
  # available.
  def set_flash_message(key, kind, options={}) #:nodoc:
    options[:scope] = "engined_cmf.#{controller_name}"
    options[:default] = Array(options[:default]).unshift(kind.to_sym)
    message = I18n.t("#{kind}", options)
    flash[key] = message if message.present?
  end

end

app/controllers/engined_cmf/dynamic_pages_controller.rb
class EnginedCmf::DynamicPagesController < EnginedCmf::ApplicationController
  inherit_resources

  defaults :route_prefix => :admin

  load_and_authorize_resource

  def create
    @dynamic_page.page.user_id = current_user.id
    create! { admin_dynamic_pages_url }
  end

  def update
    update! { admin_dynamic_pages_url }
  end

  # CanCan permissions setup
  # Use rake engined_cmf:fill_permissions for filling database with controller
  # permissions. Run this command before db:seed
  def self.permissions
    return :dynamic_page, "Pages manager", [
      [ :read, "View pages", "User can view all pages in the system.", 1 ],
      [ :create, "Create new page", "User can create new page in the system.", 2 ],
      [ :update, "Edit page", "User can edit pages in the system.", 3 ],
      [ :destroy, "Remove page", "User can remove pages from the system.", 4 ]
    ]
  end

end

app/controllers/engined_cmf/files_controller.rb
class EnginedCmf::FilesController < EnginedCmf::ApplicationController
  skip_before_filter :verify_authenticity_token, :only => ['elfinder']

  def index
    authorize! :read, File
  end

  def elfinder
    h, r = ElFinder::Connector.new(
      :root => File.join(Rails.public_path, 'uploads'),
      :allow_dot_files => false,
      :url => '/uploads',
       :perms => {
         /^\.[^\/]/ => { :read => false, :write => false, :rm => false },
         '.' => { :read => can?(:read, File), :write => can?(:write, File), :rm => can?(:destroy, File) }, # '.' is the proper way to specify the home/root directory.
         /^.*$/ => { :read => can?(:read, File), :write => can?(:write, File), :rm => can?(:destroy, File) }, # '.' is the proper way to specify the home/root directory.
       },
       :extractors => {
         'application/zip' => ['unzip', '-qq', '-o'], # Each argument will be shellescaped (also true for archivers)
         'application/x-gzip' => ['tar', '-xzf'],
       },
       :archivers => {
         'application/zip' => ['.zip', 'zip', '-qr9'], # Note first argument is archive extension
         'application/x-gzip' => ['.tgz', 'tar', '-czf'],
        }

    ).run(params)
    headers.merge!(h)
    render (r.empty? ? {:nothing => true} : {:text => r.to_json}), :layout => false
  end

  # CanCan permissions setup
  # Use rake engined_cmf:fill_permissions for filling database with controller
  # permissions. Run this command before db:seed
  def self.permissions
    return :file, "Files manager", [
      [ :read, "View files", "User can view all files in the system.", 1 ],
      [ :write, "Write files and directories", "User can write new files or create directories in the system.", 2],
      [ :destroy, "Remove files", "User can remove files or directories from the system.", 3 ]
    ]
  end

end

app/controllers/engined_cmf/images_controller.rb
class EnginedCmf::ImagesController < EnginedCmf::ApplicationController
  inherit_resources

  defaults :route_prefix => :admin

  actions :index, :new, :create, :destroy

  belongs_to :reference, :polymorphic => true
end

app/controllers/engined_cmf/index_controller.rb
# encoding: UTF-8
class EnginedCmf::IndexController < EnginedCmf::ApplicationController

  prepend_before_filter :redirect_unsigned

  def index
    @menu = [
      {
        :class => 'references',
        :selected => can?(:read, Reference),
        :image => 'engined_cmf/icon-references.png',
        :title => I18n.t('Referencie'),
        :description => I18n.t('Pridajte, vymažte alebo pozmeňte Vaše referencie'),
        :link => admin_references_path
      },
      {
        :class => 'pages',
        :selected => can?(:read, DynamicPage),
        :image => 'engined_cmf/icon-pages.png',
        :title => I18n.t('Stránky'),
        :description => I18n.t('Pridajte, vymažte alebo pozmeňte Vaše stránky'),
        :link => admin_dynamic_pages_path
      },
      {
        :class => 'files',
        :selected => can?(:read, File),
        :image => 'engined_cmf/icon-files.png',
        :title => I18n.t('Správa súborov'),
        :description => I18n.t('Nahrajte na server obrázky alebo iné súbory'),
        :link => admin_files_path
      },
      {
        :class => 'users',
        :selected => can?(:read, User),
        :image => 'engined_cmf/icon-users.png',
        :title => I18n.t('Užívatelia'),
        :description => I18n.t('Vytvorte účty pre viacerých ľudí a nastavte ich práva'),
        :link => admin_users_path
      },
      {
        :class => 'roles',
        :selected => can?(:read, Role),
        :image => 'engined_cmf/icon-roles.png',
        :title => I18n.t('Užívateľské role'),
        :description => I18n.t('Prideľte uživateľom rôzne práva'),
        :link => admin_roles_path
      },
    ]

    @grouped_menu = @menu.in_groups_of(4)
  end

  private

  def redirect_unsigned
    unless current_user
      redirect_to new_user_session_path
    end
  end

end

app/controllers/engined_cmf/profile_controller.rb
class EnginedCmf::ProfileController < EnginedCmf::ApplicationController

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in User, @user, :bypass => true
        set_flash_message :notice, :updated
        format.html { redirect_to(admin_profile_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end

  end

end

app/controllers/engined_cmf/references_controller.rb
class EnginedCmf::ReferencesController < EnginedCmf::ApplicationController
  inherit_resources

  defaults :route_prefix => :admin

  load_and_authorize_resource

  def create
    @reference.page.user_id = current_user.id
    create! { admin_references_url }
  end

  def update
    update! { admin_references_url }
  end

  # CanCan permissions setup
  # Use rake engined_cmf:fill_permissions for filling database with controller
  # permissions. Run this command before db:seed
  def self.permissions
    return :reference, "References manager", [
      [ :read, "View references", "User can view all references in the system.", 1 ],
      [ :create, "Create new reference", "User can create new references in the system.", 2 ],
      [ :update, "Edit reference", "User can edit references in the system.", 3 ],
      [ :destroy, "Remove reference", "User can remove references from the system.", 4 ]
    ]
  end

end

app/controllers/engined_cmf/roles_controller.rb
class EnginedCmf::RolesController < EnginedCmf::ApplicationController
  inherit_resources

  defaults :route_prefix => :admin

  load_and_authorize_resource

  def update
    params[:role][:permission_ids] ||= []
    super
  end

  protected

  # CanCan permissions setup
  # Use rake engined_cmf:fill_permissions for filling database with controller
  # permissions. Run this command before db:seed
  def self.permissions
    return :role, "Roles manager", [
      [ :read, "View roles", "User can view all roles in the system.", 1 ],
      [ :create, "Create new role", "User can create new roles in the system.", 2 ],
      [ :update, "Edit role", "User can edit roles in the system.", 3 ],
      [ :destroy, "Remove role", "User can remove roles from the system.", 4 ]
    ]
  end
end

app/controllers/engined_cmf/thumbnail_controller.rb
require 'RMagick'

class EnginedCmf::ThumbnailController < ApplicationController

  include EnginedCmf::ThumbnailHelper

  def show
    path = get_full_path(params[:path])
    thumb_path = get_thumbnail_path(path, params[:width], params[:height], params[:process])

    if FileTest.exists?(thumb_path)
      image = Magick::Image.read(thumb_path).first
    else
      image = generate(path, params[:width], params[:height], params[:process])
    end

    expires_in 14.days
    send_data(image.to_blob, :disposition => 'inline', :type => image.mime_type)
  end

  private

  def generate(path, width, height, process)
    process = process.to_i
    width = width.to_i
    height = height.to_i

    begin
      image = Magick::Image.read(path).first

      if process ==  PROCESS_RESIZE
        image.resize! width, height
      elsif process == PROCESS_RESIZE_TO_FILL
        image.resize_to_fill! width, height
      elsif process == PROCESS_RESIZE_TO_FIT
        image.resize_to_fit! width, height
      end

      thumb_path = get_thumbnail_path(path, params[:width], params[:height], params[:process])
      image.write(thumb_path)
      File.chmod(0666, thumb_path)
    rescue
      image = Magick::Image.from_blob(EMPTY_GIF).first
    end

    image
  end

end

app/controllers/engined_cmf/users_controller.rb
class EnginedCmf::UsersController < EnginedCmf::ApplicationController
  inherit_resources
  defaults :route_prefix => :admin

  load_and_authorize_resource

  def create
    create! { collection_url }
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    end

    respond_to do |format|
      params[:user][:role_ids] ||= []
      if @user.update_attributes(params[:user])
        if current_user.id == @user.id
          sign_in User, @user, :bypass => true
        end
        set_flash_message :notice, :updated, { :fullname => @user.fullname }
        format.html { redirect_to(collection_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # CanCan permissions setup
  # Use rake engined_cmf:fill_permissions for filling database with controller
  # permissions. Run this command before db:seed
  def self.permissions
    return :user, "Users manager", [
      [ :read, "View users", "User can view all users in the system.", 1 ],
      [ :create, "Create new user", "User can create new users in the system.", 2 ],
      [ :update, "Edit user", "User can edit users in the system.", 3 ],
      [ :destroy, "Remove user", "User can remove users from the system.", 4 ]
    ]
  end

  protected

  def resource
    @user ||= User.includes(:roles).find(params[:id])
  end

  def collection
    @users ||= User.includes(:roles).all
  end

end

app/helpers/engined_cmf/application_helper.rb
# encoding: UTF-8
module EnginedCmf::ApplicationHelper

  def title(value, variables = {})
    content_for(:title) { t value, variables }
  end

  def yield_for(symbol, default)
    output = content_for(symbol)
    output = default if output.blank?
    output
  end

  def roles_link_list(user)
    roles = []
    user.roles.each do |role|
      if can? :read, role
        roles << link_to(admin_role_path(role), :title => t('K roli')) do
          role.name
        end
      else
        roles << role.name
      end
    end
    roles.join(', ')
  end

  def author_link(author)
    if can? :read, author
      link_to(admin_user_path(author), :title => t('K užívateľovi')) do
        author.fullname
      end
    else
      author.fullname
    end
  end

  def link_to_remove_fields(name, f, *args)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", *args)
  end

  def link_to_add_fields(name, f, association, *args)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(args[0][:file].nil? ? association.to_s.singularize + "_fields" : args[0][:file], :f => builder)
    end
    args[0][:file] = nil if args[0][:file]
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", *args)
  end

end

app/helpers/engined_cmf/devise_helper.rb
module EnginedCmf::DeviseHelper

  def get_layout
    'engined_cmf/devise'
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    admin_root_path
  end

end

app/helpers/engined_cmf/files_helper.rb
module EnginedCmf::FilesHelper
end

app/helpers/engined_cmf/images_helper.rb
module EnginedCmf::ImagesHelper
end

app/helpers/engined_cmf/index_helper.rb
module EnginedCmf::IndexHelper
end

app/helpers/engined_cmf/profile_helper.rb
module EnginedCmf::ProfileHelper
  include EnginedCmf::ApplicationHelper
end

app/helpers/engined_cmf/references_helper.rb
module EnginedCmf::ReferencesHelper
  include EnginedCmf::ThumbnailHelper
end

app/helpers/engined_cmf/thumbnail_helper.rb
module EnginedCmf::ThumbnailHelper

  HOME = 'uploads'

  EMPTY_GIF = "GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;"

  PROCESS_RESIZE = 1
  PROCESS_RESIZE_TO_FILL = 2
  PROCESS_RESIZE_TO_FIT = 3

  UPLOADED_DIR = File.join(Rails.root, 'public', HOME)
  CACHE_DIR = File.join(Rails.root, 'public', 'images', 'cache')

  def get_thumbnail_uri(path, width, height, process)
    path = get_thumbnail_path(path, width, height, process)
    path.sub(/#{File.join(Rails.root, 'public')}/, '')
  end

  def get_thumbnail_path(path, width, height, process)
    File.join(CACHE_DIR, get_thumbnail_name(path, width, height, process))
  end

  def get_thumbnail_name(path, width, height, process)
    if ! FileTest.exists?(path)
      'empty.gif'
    else
      hash = Digest::MD5.hexdigest(path + '|' + File.mtime(path).to_i.to_s)
      suffix = File.extname(path)
      "preview-#{width}-#{height}-#{process}-#{hash}#{suffix}"
    end
  end

  def get_full_path(path)
    File.join(UPLOADED_DIR, path)
  end

  def thumbnail_image_path(url, width, height, process, helper = nil)
    if url !~ /.*\/#{HOME}\/(.*)/
      return url
    end

    path = url.sub(/.*\/#{HOME}\/(.*)/, '\1')
    full_path = get_full_path(path)
    thumbnail = get_thumbnail_path(full_path, width, height, process)
    if FileTest.exists?(thumbnail)
      get_thumbnail_uri(full_path, width, height, process)
    else
      helper_params = { :path => path, :width => width, :height => height, :process => process }
      if helper
        send helper, helper_params
      else
        if defined? thumbnail_path
          thumbnail_path(helper_params)
        else
          admin_thumbnail_path(helper_params)
        end
      end
    end
  end

end

app/helpers/engined_cmf/users_helper.rb
module EnginedCmf::UsersHelper
end

app/views/engined_cmf/references/_form.html.haml
- content_for :javascripts do
  = render 'engined_cmf/shared/tinymce'

= form_for([:admin, @reference]) do |f|
  - if @reference.errors.any?
    #error_explanation
      %h2
        = pluralize(@reference.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @reference.errors.full_messages.each do |msg|
          %li= msg

  = f.fields_for :page do |pf|
    .field
      = pf.label :title
      = pf.text_field :title, :class => 'page-title'

    .field
      = pf.label :alias
      = pf.text_field :alias, :class => 'page-alias'
      %a{ :class => 'page-alias-generate' }= t 'Generate'

    .field
      = f.label :city
      = f.text_field :city

    .field
      = f.label :image
      = f.text_field :image
      %a{ :class => 'file-selector', :data => { :filter => '(png|gif|jpg)$', 'filter-message' => t('Allowed are only images with suffix png, gif, jpg') } }= raw t('Browse') + '&hellip;'

    .field
      = f.label :short_content
      = f.text_area :short_content, :class => 'tinymce'

    .field
      = pf.label :content
      = pf.text_area :content, :class => 'tinymce'

    .field
      = pf.label :published_true, 'Published?'
      = pf.radio_button :published, true
      = pf.label :published_true, t('Yes')
      = pf.radio_button :published, false
      = pf.label :published_false, t('No')

    .field
      = pf.label :published_from
      = pf.text_field :published_from, { :class => 'datetimepicker' }

    .field
      = pf.label :published_to
      = pf.text_field :published_to, { :class => 'datetimepicker' }

    .field
      = pf.label :meta_author
      = pf.text_field :meta_author

    .field
      = pf.label :meta_keywords
      = pf.text_area :meta_keywords

    .field
      = pf.label :meta_description
      = pf.text_area :meta_description

    .field
      = pf.label :meta_robots
      = pf.text_field :meta_robots

  .actions
    = f.submit t('Save')

app/views/engined_cmf/references/edit.html.haml
- title 'Edit "%{title}"', :title => @reference.title

= render 'form'

- if can? :read, @reference
  = link_to t('Show'), resource_path(@reference)
- if can? :read, Reference
  = link_to t('Back'), collection_path

app/views/engined_cmf/references/index.html.haml
- title 'References overview'

%table.datatable
  %thead
    %tr
      %th= t 'Id'
      %th= t 'Title'
      %th= t 'City'
      %th= t 'Author'
      %th= t 'Created'
      %th= t 'Published?'
      %th= t 'Actions'

  %tbody
    - @references.each do |reference|
      %tr
        %td= reference.id
        %td= reference.page.title
        %td= reference.city
        %td= reference.page.user.fullname
        %td= l reference.page.created_at
        %td= reference.page.published ? t('Yes') : t('No')
        %td
          - if can? :read, reference
            = link_to t('Show'), resource_path(reference)
          - if can? :update, reference
            = link_to t('Edit'), edit_resource_path(reference)
            = link_to t('Galery'), admin_reference_images_path(reference)
          - if can? :destroy, reference
            = link_to t('Destroy'), resource_path(reference), :confirm => t('Are you sure?'), :method => :delete

-if can? :create, Reference
  = link_to t('New reference'), new_resource_path

app/views/engined_cmf/references/new.html.haml
- title 'New reference'

= render 'form'

- if can? :read, Reference
  = link_to t('Back'), collection_path

app/views/engined_cmf/references/show.html.haml
- title 'Reference "%{title}"', :title => @reference.title

%strong= t('Title') + ':'
= @reference.page.title

%br

%strong= t('Alias') + ':'
= @reference.page.alias

%br

%strong= t('City') + ':'
= @reference.city

- unless @reference.image.blank?
  %br

  %strong= t('Main image') + ':'
  %img{ :src => thumbnail_image_path(@reference.image, 300, 0, 3) }

%br

%strong= t('Short content') + ':'
= strip_tags @reference.short_content

%br

%strong= t('Content') + ':'
= truncate strip_tags(@reference.page.content), :length => 300, :separator => ' '

%br

%strong= t('Published?')
= @reference.page.published ? t('Yes') : t('No')

- if @reference.page.published_from
  %br
  %strong= t('Published from') + ':'
  = l @reference.page.published_from

- if @reference.page.published_to
  %br
  %strong= t('Published to') + ':'
  = l @reference.page.published_to

%br

%strong= t('Created') + ':'
= l @reference.page.created_at

%h2= t 'Meta information'
%strong= t('Meta description') + ':'
= @reference.page.meta_description

%br

%strong= t('Meta keywords') + ':'
= @reference.page.meta_keywords

%br

%strong= t('Meta author') + ':'
= @reference.page.meta_author

%br

%strong= t('Meta robots') + ':'
= @reference.page.meta_robots

%br

- if can? :edit, @reference
  = link_to t('Edit'), edit_resource_path(@reference)
  = link_to t('Galery'), admin_reference_images_path(@reference)
- if can? :read, Reference
  = link_to t('Back'), collection_path